CodeWars ! create pre-push !

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,19 @@
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+#!/bin/bash
+
+commit_denied=false
 
 if git diff --cached --name-only | grep -q "^JavaScript/"; then
-    echo "Коммит запрещен: изменения в директории 'forbidden-dir' не могут быть закоммичены."
-    exit 1
+    git reset JavaScript
+    echo -e "\033[31mCommit denied: changes in the 'JavaScript' directory cannot be committed.\033[0m"
+    commit_denied=true
 fi
 
+if git diff --cached --name-only | grep -q "^SQL/"; then
+    git reset SQL
+    echo -e "\033[31mCommit denied: changes in the 'SQL' directory cannot be committed.\033[0m"
+    commit_denied=true
+fi
+
+if [ "$commit_denied" = true ]; then
+    exit 1
+fi
